<a href="https://colab.research.google.com/github/pretellpo/Introduction-to-Machine-Learning-with-Python/blob/master/Chapter1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
print("hello world")

hello world


In [0]:
import numpy as np
from scipy import sparse
import matplotlib.pyplot as plt

In [0]:
from sklearn.datasets import load_iris
iris_dataset = load_iris()

In [4]:
print("keys of iris dataset: {}".format(iris_dataset.keys()))

keys of iris dataset: dict_keys(['data', 'target', 'target_names', 'DESCR', 'feature_names', 'filename'])


In [0]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(iris_dataset['data'], iris_dataset['target'])

In [8]:
print("X_train:")
print(X_train[:5])
print("y_train:")
print(y_train[:5])

X_train:
[[7.  3.2 4.7 1.4]
 [4.4 2.9 1.4 0.2]
 [5.1 2.5 3.  1.1]
 [5.1 3.5 1.4 0.2]
 [5.7 2.5 5.  2. ]]
y_train:
[1 0 1 0 2]


In [0]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=1)

In [10]:
knn.fit(X_train,y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=1, p=2,
                     weights='uniform')

In [0]:
X_new = np.array([[5,2.9,1,0.2]])

In [12]:
prediction = knn.predict(X_new)
print("Prediction: {}".format(prediction))
print("Prediction target name: {}".format(iris_dataset['target_names'][prediction]))

Prediction: [0]
Prediction target name: ['setosa']


In [13]:
y_pred = knn.predict(X_test)
print("Test score: {:.2f}".format(knn.score(X_test,y_test)))

Test score: 0.95
